<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * Partitioned by month on created_at, so old months are dropped whole instead of deleted row by row. PostgreSQL
     * needs the partition key inside the primary key. The partitions created here cover the current and next month;
     * the events:partitions command prepares the following ones.
     */
    public function up(): void
    {
        DB::statement(<<<'SQL'
            CREATE TABLE events (
                id bigint GENERATED BY DEFAULT AS IDENTITY,
                type varchar(32) NOT NULL,
                user_id bigint NULL REFERENCES users (id) ON DELETE SET NULL,
                visitor_hash varchar(64) NULL,
                copypasta_id char(26) NULL REFERENCES copypastas (id) ON DELETE SET NULL,
                context jsonb NOT NULL DEFAULT '{}'::jsonb,
                created_at timestamp(0) without time zone NOT NULL,
                PRIMARY KEY (id, created_at)
            ) PARTITION BY RANGE (created_at)
            SQL);

        DB::statement('CREATE INDEX events_user_id_created_at_index ON events (user_id, created_at)');
        DB::statement('CREATE INDEX events_copypasta_id_created_at_index ON events (copypasta_id, created_at)');

        $currentMonth = now()->startOfMonth();

        foreach ([$currentMonth, $currentMonth->copy()->addMonth()] as $month) {
            DB::statement(sprintf(
                "CREATE TABLE IF NOT EXISTS events_y%sm%s PARTITION OF events FOR VALUES FROM ('%s') TO ('%s')",
                $month->format('Y'),
                $month->format('m'),
                $month->format('Y-m-d'),
                $month->copy()->addMonth()->format('Y-m-d'),
            ));
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS events');
    }
};
